config/routes.rb
Rails.application.routes.draw do
  get 'static/homepage'

  devise_for :users
  get 'pages/info'
  resources :helpers do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#homepage'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :helper
  belongs_to :user
end

app/models/helper.rb
class Helper < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_helper
  before_action :find_comment, only: [:destroy, :edit, :update, :comment_owner]
  before_action :comment_owner, only: [:destroy, :edit, :update]

  def create
    @comment = @helper.comments.create(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.save

    if @comment.save
      redirect_to helper_path(@helper)
    else
      render 'new'
    end
  end

  def destroy
    @comment.destroy
    redirect_to helper_path(@helper)
  end

  def edit; end

  def update
    if @comment.update(params[:comment].permit(:content))
      redirect_to helper_path(@helper)
    else
      render 'edit'
    end
  end

  private

  def find_helper
    @helper = Helper.find(params[:helper_id])
  end

  def find_comment
    @comment = @helper.comments.find(params[:id])
  end

  def comment_owner
    unless current_user.id == @comment.user_id
      flash[:notice] = 'This comment is not editable by you'
      redirect_to @helper
    end
  end
end

app/controllers/helpers_controller.rb
class HelpersController < ApplicationController
  before_action :set_helper, only: [:show, :edit, :update, :destroy]

  # GET /helpers
  # GET /helpers.json
  def index
    @helpers = Helper.all
  end

  # GET /helpers/1
  # GET /helpers/1.json
  def show
    @comments = Comment.where(helper_id: @helper)
  end

  # GET /helpers/new
  def new
    @helper = Helper.new
  end

  # GET /helpers/1/edit
  def edit
  end

  # POST /helpers
  # POST /helpers.json
  def create
    @helper = Helper.new(helper_params)

    respond_to do |format|
      if @helper.save
        format.html { redirect_to @helper, notice: 'Helper was successfully created.' }
        format.json { render :show, status: :created, location: @helper }
      else
        format.html { render :new }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /helpers/1
  # PATCH/PUT /helpers/1.json
  def update
    respond_to do |format|
      if @helper.update(helper_params)
        format.html { redirect_to @helper, notice: 'Helper was successfully updated.' }
        format.json { render :show, status: :ok, location: @helper }
      else
        format.html { render :edit }
        format.json { render json: @helper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /helpers/1
  # DELETE /helpers/1.json
  def destroy
    @helper.destroy
    respond_to do |format|
      format.html { redirect_to helpers_url, notice: 'Helper was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_helper
      @helper = Helper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def helper_params
      params.require(:helper).permit(:name, :alias, :age, :years_of_experience, :rating, :rates, :speciality, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/helpers_helper.rb
module HelpersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/comments/_comment.html.erb
<i><p> Total number of comments: <%= pluralize(@comments.count, "") %> <p></i>

<% @comments.each do |comment| %>

  <p><i><b><%= comment.user.email %></b></i></p>
  <p><%= comment.content %></p>
  <% if current_user == comment.user %>
    <i><%= link_to "Delete comment", [comment.helper, comment], method: :delete %></i>
    <i><%= link_to "Edit comment", edit_helper_comment_path(comment.helper, comment) %></i>
  <% end %>
<% end %>

<br>
<br>
<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<br>
<%= form_for([@helper, @helper.comments.build]) do |f| %>
  <%= f.text_area :content %>
  <%= f.submit %>

<% end %>

app/views/comments/edit.html.erb
<%= form_for([@helper, @comment]) do |f| %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Helper</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.helper_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Helper:</strong>
  <%= @comment.helper_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/helpers/_form.html.erb
<%= form_for(helper) do |f| %>
  <% if helper.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(helper.errors.count, "error") %> prohibited this helper from being saved:</h2>

      <ul>
      <% helper.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="form-group">
    <%= f.label :alias %>
    <%= f.text_field :alias %>
  </div>

  <div class="form-group">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="form-group">
    <%= f.label :years_of_experience %>
    <%= f.number_field :years_of_experience %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.number_field :"rating" %>
  </div>

  <div class="form-group">
    <%= f.label :rates %>
    <%= f.number_field :rates %>
  </div>

  <div class="form-group">
    <%= f.label :speciality %>
    <%= f.text_area :speciality %>
  </div>

  <div class="form-group">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

</div>
<% end %>

app/views/helpers/edit.html.erb
<h1>Editing Helper</h1>

<%= render 'form', helper: @helper %>

<%= link_to 'Show', @helper %> |
<%= link_to 'Back', helpers_path %>

app/views/helpers/index.html.erb
<% @helpers.in_groups_of(3) do |group| %>
  <div class="row">
    <% group.compact.each do |helper| %>
      <div class="col-md-4">
        <%= image_tag helper.picture_url, width: '50%' if helper.picture.present?%>
        <h4><%= link_to helper.name, helper %></h4>
        <p>You can call me: <%= helper.alias %> </p>
        <p>I can do: <%= helper.speciality %> </p>
        <p>Rating: <%= helper.rating %>/10</p>
        <p>Years of Experience: <%= helper.years_of_experience %> years</p>
        <p>Rates: $<%= helper.rates %>/hr</p>
        <p>Age: <%= helper.age %> years old</p>
      </div>
    <% end %>
  </div>
<% end %>

app/views/helpers/new.html.erb
<h1>Add New Helper Here</h1>
<br><br>

<div class="container">
<%= render 'form', helper: @helper %>

<div class="container">
  <%= link_to 'Back', helpers_path %>
</div>

</div>

app/views/helpers/show.html.erb
<div class="tile is-ancestor">
    <div class="tile is-vertical is-8">
        <div class="tile">
            <div class="tile is-parent is-vertical">
                <article class="tile is-child box">
                    Hi, my name is
                    <strong><%= @helper.name %></strong>
                    and you can address me as
                    <%= @helper.alias %>. I am
                    <%= @helper.age %>
                    this year and I have
                    <%= @helper.years_of_experience %>
                    years in providing cleaning services.
                    <br><br>
                    <strong> Rates:$<%= @helper.rates%>/hr </strong>
                    <br>
                    <strong> Specialty: <%= @helper.speciality%></strong>

                </article>
                <article class="tile is-child box">
                  <%= render 'comments/comment' %>
                </article>


            </div>
            <div class="tile is-parent">
                <article class="tile is-child box">
                    <%= image_tag(@helper.picture_url, width: 400) if @helper.picture.present? %>
                </article>
            </div>
        </div>
    </div>
</div>

<!--
<p>
  <strong>Name:</strong>
  <%= @helper.name %>
</p>

<p>
  <strong>Alias:</strong>
  <%= @helper.alias %>
</p>

<p>
  <strong>Age:</strong>
  <%= @helper.age %>
</p>

<p>
  <strong>Years of experience:</strong>
  <%= @helper.years_of_experience %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @helper.rating %>
</p>

<p>
  <strong>Rates:</strong>
  <%= @helper.rates %>
</p>

<p>
  <strong>Speciality:</strong>
  <%= @helper.speciality %>
</p>

</div>

<p>
  <%= image_tag(@helper.picture_url, width: 200) if @helper.picture.present? %>
</p>

<%= render 'comments/comment' %>

<%= link_to 'Edit', edit_helper_path(@helper) %> |
<%= link_to 'Back', helpers_path %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Help Hero</title>
        <%= csrf_meta_tags %>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bulma/0.4.0/css/bulma.css">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bulma/0.4.0/css/bulma.css.map">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bulma/0.4.0/css/bulma.min.css">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bulma/0.4.0/css/bulma.min.css.map">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/"><img src="http://i.imgur.com/sx1PYOT.png" alt="My Logo" height="40" width="40"></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="/helpers">Helpers</a>
                        </li>
                        <li ><%= link_to 'New Helper', new_helper_path %></li>
                    </ul>
                    <p class="navbar-text pull-right">
                        <% if user_signed_in? %>
                        Logged in as
                        <strong><%= current_user.email %></strong>.
                        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
                        |
                        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                    <% else %>
                        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
                        |
                        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
                        <% end %>
                    </div>
                </div>
            </nav>
            <br>
            <div class="container">
                <% if notice %>
                <p class="alert alert-success"><%= notice %></p>
                <% end %>
                <% if alert %>
                <p class="alert alert-danger"><%= alert %></p>
                <% end %>
                <%= yield %>
            </div>
            <br>
<br><br><br><br><br><br>
            <footer class="footer">
                <div class="container">
                    <p class="text-muted">&copy; Help Hero 2017</p><br>
                    <a target="_blank" title="follow me on Twitter" href="http://www.twitter.com"><img alt="follow me on Twitter" src="http://i.imgur.com/FHOcVjk.png" height="42" width="42" border=0></a>
                    <a target="_blank" title="follow me on Facebook" href="http://www.facebook.com"><img alt="follow me on Facebook" src="http://i.imgur.com/XB8Ztxu.png" height="42" width="42" border=0></a>
                    <a target="_blank" title="follow me on Instagram" href="http://www.instagram.com"><img alt="follow me on Instagram" src="http://i.imgur.com/Yp2hULF.png" height="42" width="42" border=0></a>
                    <a target="_blank" title="Call me on Whatsapp" href="http://www.contact.com"><img alt="Call me on Whatsapp" src="http://i.imgur.com/IYx4mAt.png" height="42" width="42" border=0></a>

                </div>
            </footer>
            <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
        </body>
    </html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>